# Configuration without Perceptual Loss
# Edge sensors without perceptual loss for faster training

# Model Architecture
model:
  use_fourier: false
  use_perceptual_loss: false
  input_shape: [128, 256, 1]
  latent_dims: 8
  n_base_features: 64

# Sensor Configuration
sensors:
  layout: "edge"
  n_sensors: 8

# Training Parameters
training:
  vae_epochs: 80   # Fewer epochs without perceptual loss
  flr_epochs: 150
  vae_learning_rate: 0.0001
  flr_learning_rate: 0.00005
  batch_size: 12   # Larger batch without perceptual loss
  test_split: 0.2
  shuffle_buffer: 3000
  patience: 30
  reduce_lr_patience: 7
  gradient_clip_norm: 1.0      # Gradient clipping norm (1.0 is conservative)

# Data Configuration
data:
  dataset_base_path: "data/datasets"
  
# Output Configuration
output:
  checkpoint_base_dir: "./checkpoints"
  logs_base_dir: "./logs"
  save_best_model: true
  save_last_model: true

# Reproducibility
random_seed: 42
