# Edge Sensor Layout Configuration with Fourier Enhancement
# Fourier-enhanced edge sensors

# Model Architecture
model:
  use_fourier: true
  use_perceptual_loss: true
  input_shape: [128, 256, 1]
  latent_dims: 8
  n_base_features: 64

# Sensor Configuration
sensors:
  layout: "random"
  n_sensors: 32

# Training Parameters
training:
  vae_epochs: 250  # Slightly more epochs for Fourier
  flr_epochs: 150
  vae_learning_rate: 0.0001
  flr_learning_rate: 0.0001
  batch_size: 8    # Smaller batch for Fourier due to memory
  test_split: 0.2
  shuffle_buffer: 1000
  patience: 100
  reduce_lr_patience: 20
  gradient_clip_norm: 2.0      # Gradient clipping norm (1.0 is conservative)


# Data Configuration
data:
  dataset_base_path: "data/datasets"
  
# Output Configuration
output:
  checkpoint_base_dir: "./checkpoints"
  logs_base_dir: "./logs"
  save_best_model: true
  save_last_model: true

# Reproducibility
random_seed: 42
